### ISSUE TITLE
居然是JavaScript

### ISSUE THREAD

**Issue by huhanwj** [chang2000/Maria-s-Gallery#3]
这就是coder的爱情吗，i了i了

**Comment by chang2000** [comment]
快點返去讀書做嘢

> 这就是coder的爱情吗，i了i了

**Comment by Maria-draws** [comment]
> 这就是coder的爱情吗，i了i了

i了i了

**Comment by huhanwj** [comment]
> 快點返去讀書做嘢
> 
> > 这就是coder的爱情吗，i了i了

不要，我老板天天push我都没空读书uu
